#cloud-config
users:
  - name: ${deploy_username}
    groups: [sudo]
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
      - ${deploy_ssh_pubkey}

package_update: true
package_upgrade: true
packages:
  - ca-certificates
  - curl
  - gnupg

runcmd:
  - install -m 0755 -d /etc/apt/keyrings
  - bash -c 'curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg'
  - chmod a+r /etc/apt/keyrings/docker.gpg
  - bash -c 'echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian $(. /etc/os-release && echo $${VERSION_CODENAME}) stable" > /etc/apt/sources.list.d/docker.list'
  - apt-get update
  - apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
  - usermod -aG docker ${deploy_username}
  - systemctl enable --now docker
  - mkdir -p /opt/constructa