#cloud-config
ssh_pwauth: false
disable_root: true

users:
  - name: ${deploy_username}
    groups: [sudo]
    shell: /bin/bash
    ssh_authorized_keys:
      - ${deploy_ssh_pubkey}

package_update: true
package_upgrade: true
packages:
  - ca-certificates
  - curl
  - gnupg
  - ufw
  - fail2ban
  - git

write_files:
  - path: /etc/fail2ban/jail.d/sshd.local
    permissions: '0644'
    owner: root:root
    content: |
      [sshd]
      enabled = true
      port    = 22
      filter  = sshd
      logpath = %(sshd_log)s
      maxretry = 5
      bantime  = 1h
      findtime = 10m
      # Whitelist your Terraform-var-provided CIDR to reduce false positives
      ignoreip = 127.0.0.1/8 ::1 ${allowed_ssh_cidr}

runcmd:
  # Install Docker Engine + Compose plugin
  - install -m 0755 -d /etc/apt/keyrings
  - bash -c 'curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg'
  - chmod a+r /etc/apt/keyrings/docker.gpg
  - bash -c 'echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian $(. /etc/os-release && echo $${VERSION_CODENAME}) stable" > /etc/apt/sources.list.d/docker.list'
  - apt-get update
  - apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
  - systemctl enable --now docker

  # UFW: only SSH (from your CIDR) and HTTP/HTTPS
  - ufw default deny incoming
  - ufw default allow outgoing
  - ufw allow from ${allowed_ssh_cidr} to any port 22 proto tcp
  - ufw allow 80/tcp
  - ufw allow 443/tcp
  - ufw --force enable

  # Fail2ban
  - systemctl enable --now fail2ban
