#cloud-config
users:
  - name: ${deploy_username}
    groups: [sudo]
    shell: /bin/bash
    sudo: ALL=(ALL) ALL
    ssh_authorized_keys:
      - ${deploy_ssh_pubkey}

package_update: true
package_upgrade: true
packages:
  - ca-certificates
  - curl
  - gnupg
  - git
  - ufw
  - apt-transport-https
  - wget
  - software-properties-common
  - dirmngr
  - lsb-release

runcmd:
  # Install Docker (required by Dokku)
  - install -m 0755 -d /etc/apt/keyrings
  - bash -c 'curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg'
  - chmod a+r /etc/apt/keyrings/docker.gpg
  - bash -c 'echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian $(. /etc/os-release && echo $${VERSION_CODENAME}) stable" > /etc/apt/sources.list.d/docker.list'
  - apt-get update
  - apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
  - systemctl enable --now docker

  # Wait for Docker to be ready
  - sleep 10
  - docker version

  # Install Dokku (latest stable version)
  - |
    cd /tmp
    wget https://dokku.com/install/v0.36.7/bootstrap.sh
    chmod +x bootstrap.sh
    DOKKU_TAG=v0.36.7 ./bootstrap.sh

  # Configure firewall for Dokku
  - ufw allow OpenSSH
  - ufw allow http
  - ufw allow https
  - ufw --force enable

  # Basic Dokku configuration
  - dokku domains:add-global ex0.dev
  - dokku config:set --global DOKKU_LETSENCRYPT_EMAIL=admin@ex0.dev
